name: build and publish

on:
  push:
    branches:
      - "master"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Set Up Git Identity
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae' | xargs)"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          pip install pipx==1.2.1

      - name: Update Version and Changelog
        run: |
          pipx install python-semantic-release==8.3.0
          semantic-release -v version --no-vcs-release --no-commit
          differences=$(git diff | xargs)

          if [ -z "$differences" ]; then
            echo "No changes needed"
            exit 0
          fi

          echo "Version and/or Changelog needs to be updated"

          git add --all
          git commit -m "chore(release): bump version and update changelog"
          git push

          echo "::error::The version and/or Changelog is outdated"
          echo "$differences"
          exit 1

      - name: Build package
        run: |
          pipx run build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        
      - name: Create Git Tag
        run: |
          version_number=$(semantic-release -v version --print)
          git tag "v$version_number"
          git push origin --tags
